#!/usr/bin/env bash

rm *.pem
consul tls ca create
consul tls cert create -dc dc1 -server
consul tls cert create -dc dc2 -server

token=$(secint mint -issuer auto-config-cluster -ttl 1h -node auto-config-client -priv-key dc1-server-consul-0-key.pem)

# inject token into consul connect ca config
sed -i.bu "s/\"token\":.*/\"token\": \"$token\",/" examples/auto_config/client.json
rm -rf examples/auto_config/client.json.bu

IFS=$"\n"
pub=$(cat dc1-server-consul-0.pem)
sed -i.bu "s/\"jwt_validation_pub_keys\":.*/\"jwt_validation_pub_keys\": [\"$pub\"],/" examples/auto_config/server_dc1.json
sed -i.bu "s/\"jwt_validation_pub_keys\":.*/\"jwt_validation_pub_keys\": [\"$pub\"],/" examples/auto_config/server_dc2.json
rm -rf examples/auto_config/server_dc1.json.bu
rm -rf examples/auto_config/server_dc2.json.bu
