#!/usr/bin/env bash

# these ports are also hardcoded in server_template.json
listener=18000
admin=19000
for dc in dc1 dc2 dc3; do
	grpc=$(jq -r ".servers.\"s1.$dc\".grpc_port" cluster.json)
	http=$(jq -r ".servers.\"s1.$dc\".http_port" cluster.json)

	# reusing the client certs for envoy
	consul connect envoy -mesh-gateway -register -service "$dc-gateway" \
		-address "127.0.0.1:$listener" \
		-wan-address "127.0.0.1:$listener" \
		-admin-bind "127.0.0.1:$admin" \
		-grpc-addr "https://localhost:$grpc" \
		-http-addr="http://localhost:$http" \
		-expose-servers \
		-ca-file "./consul-agent-ca.pem" -client-cert "./${dc}-client-consul-0.pem" -client-key "./${dc}-client-consul-0-key.pem" \
		&

	((listener=$listener+1))
	((admin=$admin+1000))
done

consul config write examples/wan_fed/proxy-default.json
