#!/usr/bin/env bash

rm *.pem
consul tls ca create

for dc in dc1 dc2; do # 2 dcs configured

	# setup client certs for each dc
	consul tls cert create -dc $dc -client
	cp examples/wan_fed/client_template.json examples/wan_fed/client_${dc}.json
	cert="$dc-client-consul-0"
	fileName="examples/wan_fed/client_${dc}.json"
	sed -i.bu "s/\"cert_file\":.*/\"cert_file\": \".\/${cert}.pem\",/" $fileName
	sed -i.bu "s/\"key_file\":.*/\"key_file\": \".\/${cert}-key.pem\",/" $fileName

	# setup server certs
	for s in 1 2 3; do # 3 servers by default
		consul tls cert create -dc $dc -node "s$s" -server 
		i=$(expr $s - 1)
		cp examples/wan_fed/server_template.json examples/wan_fed/server_${dc}_s${s}.json
		cert="$dc-server-consul-$i"
		fileName="examples/wan_fed/server_${dc}_s${s}.json"
		sed -i.bu "s/\"cert_file\":.*/\"cert_file\": \".\/${cert}.pem\",/" $fileName
		sed -i.bu "s/\"key_file\":.*/\"key_file\": \".\/${cert}-key.pem\",/" $fileName

		# configure primary_datacenters only in secondaries
		if [ "$dc" != "dc1" ]; then
			sed -i.bu "s/\"primary_gateways\":.*/\"primary_gateways\": [\"localhost:18101\"],/" $fileName
		fi
	done
done
rm -rf examples/wan_fed/*.bu
